name: pub_mirror
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Hui Yiqun <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  # pub_client: ^3.0.2
  pub_client:
    git: git://github.com/huiyiqun/pub_client.git
  executor: ^2.1.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
