name: pub_mirror
description: A sample command-line application.
version: 0.1.5
homepage: https://github.com/huiyiqun/pub-mirror
author: Hui Yiqun <i@huiyiqun.me>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  # pub_client: ^3.0.2
  pub_client:
    git: git://github.com/huiyiqun/pub_client.git
  executor: ^2.1.2
  path: ^1.6.2
  args: ^1.5.1
  http: ^0.11.3+17
  pedantic: ^1.5.0

dev_dependencies:
  pedantic: ^1.5.0

executables:
  pub_mirror:
